### ISSUE TITLE
Create a cool looking turtle!

### ISSUE THREAD

**Issue by BiLachner** [BiLachner/TurtleMiner#1]
Is anyone able to create in blender a nice turtle with feet and head, mostly green, a bit like a block but even a bit rounded.

The turtle should become look more and more "intelligent" as the turtle learns more and more (or better the owner/user learns )
- First turtle with no additional things
- A turtle connected to a remote control with something like an aerial to have contact to the turtle
- A turtle that can dig with a pickaxe
- A turtle that has got an inventory with a backpack
- ...

You should add some features or just change the textures to show the the turtle learned

**Comment by octacian** [comment]
I've added one more turtle, and renamed the current turtle itemstrings to make a bit more sense. The turtle I added if from my branch of digicompute. Right now, I'm working on a text based editor.

Instead of having a bunch of different turtles with different capabilities, I think we should make an inventory-based upgrade system that unlocks new features without having to make different turtles. After the basic system works, we can worry about visible changes on the node.

BTW, your current turtle, I'm sorry... The textures and model, IK some kids supposedly like it and think it's funny, but from what I've asked people they think it's funny cause it looks "stupid." At least you should make the textures 16x16 or _maybe_ 32x32. I personally believe that they should give the idea of not an animal, but a robot. Making them appear as animals just makes absolutely no sense.

**Comment by BiLachner** [comment]
As we have may be different target groups I'll ask mine what they think about it. 

The appearance is only one little part. The main goals are of cause others. Anything can changed quite simply!
