### ISSUE TITLE
Prevent Breaking of Unbreakable Blocks

### ISSUE THREAD

**Issue by BiLachner** [BiLachner/TurtleMiner#5]
I hope the name " show-jumping course " is translated correctly? 
The idea is that there should be blocks that can be used to give some exercises and that are not diggable by the turtle. One that is transparent and one that is not transparent. 

There are two ways to solve this problem:
- define some of the default blocks that are not diggable (diamond, obsidian, obsidian-glass...)
- create two new blocks

**Comment by octacian** [comment]
This issue will be solved by what I'm working on right now, which is making it so that a turtle cannot break blocks that the player owning it would not be able to break. The turtle still would not require tools, but would be unable to break blocks that no tool could. Renaming to "Prevent breaking of Unbreakable Blocks"

**Comment by octacian** [comment]
I've opted for something quite simple, which involves a single function checking whether the node is in the unbreakable class. All that is required anywhere that this function needs to be used, is a simple if statement:

```
if turtleminer.is_breakable(pos) then ... end
```

The function returns `true` if the node is breakable and `nil` if it is unbreakable.

Closing.
